### ISSUE TITLE
Need to scroll the list to retrieve all of the items if there are more than ~12 items

### ISSUE THREAD

**Issue by backcountrymountains** [jtbnz/amazon_shopping_list#3]
I have a very disorganized and long shopping list (60 items that I never looked at because I used todoist and not the amazon interface, don't judge). When I use this tool, it only grabs the first 12 or so visible items in the ```virtual-list``` div (container?). There is a ```scroll``` event that dynamically adds more items to the list that I can use to grab the rest of the items. I have no idea what I'm doing but using a combination of commands I can scroll the list:

Get array of divs whose parents have ```offsetTop```
```var innerDiv = $$('.inner') ```

Get the ```offsetTop``` of the last item in the ```innerDiv``` array
```innerDiv[innerDiv.length -1].parentElement.offsetTop```

Get the ```virtual-list``` thing
```var list = $('.virtual-list')```

Scroll the list to the ```offsetTop``` of the last item
```list.scrollTop = innerDiv[innerDiv.length -1].parentElement.offsetTop```

This seems clunky. Is there a way to directly trigger the ```scroll``` event? Is it possible to make the ```virtual-list``` div container thing so huge that all off the list items would be visible without scrolling? I don't know how web pages work.

**Comment by backcountrymountains** [comment]
I can get the following to work in the console, but haven't figured out how to get it to work with puppeteer:
```
let i = 0;
let formattedItems = [];
 
do {
	var list = $('.virtual-list')
	list.scrollTop = i*1000
	var itemTitles = $$(".virtual-list .item-title")
	var textList = itemTitles.map(item => item.childNodes[0].textContent.trim())
	formattedItems.push(...textList)
	console.log(formattedItems)
	i++
}
while (i*1000 < list.scrollHeight)

//deduplicate	
formattedItems.filter((item,index) => formattedItems.indexOf(item) === index);
```

**Comment by jtbnz** [comment]
hmm, the reason I ended up using pupeteer was that there seems to be a delay on the amazon pages and the page.waitforselector and page.waitfornavigation were needed.

I found this approach https://stackoverflow.com/questions/51529332/puppeteer-scroll-down-until-you-cant-anymore which might work.

**Comment by backcountrymountains** [comment]
I don't know how to program and I definitely don't know puppeteer (I keep spelling it wrong!) but I got the following code to barf out my whole long shopping list:
```
let formattedItems = [];
let i = 0;
let itemTitles = [];
let scrollT = "";
let scrollH = "";
const scrollable_section = '.virtual-list';

do {
        await scrollDown(page, i);
        itemTitles = await page.$$eval(".virtual-list .item-title", items => items.map(item => item.textContent.trim()) );
        i++;
        formattedItems.push(...itemTitles);
        scrollH = await page.$eval('.virtual-list', el => el.scrollHeight)
}
while (i*500 < scrollH)

async function scrollDown(page, i) {
        const dist = i*500;
        await page.waitForSelector('.virtual-list');
        await page.evaluate(
                (selector, dist) => {
                        const scrollableSection = document.querySelector(selector);
                        scrollableSection.scrollTop = dist;
                },
                scrollable_section, dist);
        scrollT = await page.$eval('.virtual-list', el => el.scrollTop)
};

  // Deduplicate
  formattedItems = formattedItems.filter((item,index) => formattedItems.indexOf(item) === index);
```

**Comment by jtbnz** [comment]
updated script-otp to handle long lists - thanks!
